apiVersion: v1
kind: Service
metadata:
  name: error-tracker-service
  labels:
    app: error-tracker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  type: {{ .Values.service.type }}
  selector:
    app: error-tracker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP