apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-tracker-deploy
  labels:
    app: error-tracker

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: error-tracker

  template:
    metadata:
      labels:
        app: error-tracker
    
    spec:
      containers:
      - name: error-tracker-container
        image: abhi0874/error-tracker:v1
        ports:
        - containerPort: 3000