name: error-tracker-workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
      - 'k8s/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Cache Next.js build output
      uses: actions/cache@v3
      with:
        path: web/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('web/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-

    - name: Install Dependencies
      run: |
        cd web
        npm install

    - name: Build the Application
      run: |
        cd web
        npm run build

  Build-Docker-Image:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image 
      uses: docker/build-push-action@v6
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/error-tracker:${{github.run_id}}
        no-cache: true

  Security-Scan:
    needs: Build-Docker-Image
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Install Trivy
      uses: aquasecurity/trivy-action@0.3.0
      with:
        scan-type: 'image'
        image-ref: '${{secrets.DOCKER_USERNAME}}/error-tracker:${{github.run_id}}'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true

  Update-Helm-Chart:
    needs: Security-Scan
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      with:
        token: ${{secrets.GIT_TOKEN}}

    - name: Update tag in helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/error-tracker-chart/values.yaml

    - name: Commit and Push Changes
      run: |
        git config --global user.email "kumar27ankitsingh@gmail.com"
        git config --global user.name "Ankit Kumar"
        git add helm/error-tracker-chart/values.yaml
        git commit -m "update tag in helm chart"
        git push